# Generated by Django 5.1.6 on 2025-04-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('date', models.DateField()),
                ('type_of_data', models.CharField(blank=True, choices=[('LN', 'Latest News'), ('UE', 'Upcoming Events'), ('NB', 'Notice Board')], max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='Miscellaneous', max_length=255),
        ),
    ]
